# Generated by Django 3.0.6 on 2020-10-05 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('img1', models.ImageField(upload_to='shop/images')),
                ('img2', models.ImageField(blank=True, upload_to='shop/images')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='shop/images')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('categoryid', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Footwear', 'Footwear'), ('Grocery', 'Grocery')], default='Clothing', max_length=50)),
                ('productrating', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersQuery',
            fields=[
                ('srNo', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('currentTime', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=500)),
                ('likes', models.IntegerField()),
                ('query_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product_Detail')),
                ('query_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Detail',
            fields=[
                ('srNo', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('rating_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product_Detail')),
                ('rating_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('srNo', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
                ('currentTime', models.DateTimeField(auto_now_add=True)),
                ('review_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product_Detail')),
                ('review_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('product_ids', models.TextField(default='', max_length=1000)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('delivery_date', models.DateField(default='')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('product_data', jsonfield.fields.JSONField()),
                ('order_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
