# Generated by Django 3.0.8 on 2020-11-09 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='message',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='review_product_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.Product_Detail'),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='review_user_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating_detail',
            name='rating',
            field=models.CharField(choices=[('4', '4'), ('2', '2'), ('1', '1'), ('3', '3'), ('5', '5')], default='3', max_length=100),
        ),
        migrations.AlterField(
            model_name='rating_detail',
            name='rating_product_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.Product_Detail'),
        ),
        migrations.AlterField(
            model_name='rating_detail',
            name='rating_user_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
