# Generated by Django 3.0.8 on 2020-11-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201109_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_detail',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('5', '5'), ('2', '2'), ('4', '4')], default='3', max_length=100),
        ),
    ]
