# Generated by Django 3.0.8 on 2020-11-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201110_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_detail',
            name='rating',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('2', '2'), ('1', '1'), ('3', '3')], default='3', max_length=100),
        ),
    ]
