# Generated by Django 3.0.6 on 2020-11-10 18:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201110_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='product_specification',
            field=jsonfield.fields.JSONField(default={'color': 'red', 'quantity': 5}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating_detail',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('1', '1'), ('4', '4'), ('2', '2')], default='3', max_length=100),
        ),
    ]
