# Generated by Django 3.0.8 on 2020-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201110_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_review',
            old_name='currentTime',
            new_name='reviewTime',
        ),
        migrations.AlterField(
            model_name='rating_detail',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('4', '4'), ('3', '3'), ('5', '5')], default='3', max_length=100),
        ),
    ]
