# Generated by Django 3.0.8 on 2020-11-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201111_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_detail',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('5', '5'), ('3', '3'), ('4', '4')], default='3', max_length=100),
        ),
    ]
