# Generated by Django 3.0.6 on 2020-11-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201111_1830'),
        ('shop', '0007_auto_20201111_1737'),
    ]

    operations = [
    ]
