# Generated by Django 3.0.8 on 2020-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201119_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='productrating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating_detail',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('2', '2'), ('4', '4'), ('5', '5')], default='3', max_length=100),
        ),
    ]
