# Generated by Django 3.0.8 on 2020-11-30 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_auto_20201119_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_detail',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('3', '3'), ('5', '5'), ('4', '4')], default='3', max_length=100),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product_Detail')),
                ('wishlist_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
